version: '3.5'

services:
  flyway:
    container_name: flyway_person_hub
    image: flyway/flyway:7.12.1-alpine
    command: -url=jdbc:postgresql://host.docker.internal:5432/person-hub -schemas="person-hub" -user=postgres -password=P@ssw0rd migrate
    volumes:
      - ../sql:/flyway/sql