# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# specific path build
trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - PersonHubApi

resources:
- repo: self

pool:
  vmImage: Ubuntu-16.04

variables:
- group: person-hub-api
- name: tag
  value: '$(Build.BuildId)'
- name: imageRepository
  value: 'person-hub-api'
- name: imageName
  value: 'personhub.azurecr.io/$(imageRepository):$(tag)'
- name: appServiceName
  value: 'person-hub'
- name: dockerRegistryServiceConnection
  value: 'personhubACR'
- name: azureSubscription
  value: $(azure-subscription)
- name: dockerRegistryPassword
  value: $(docker-registry-password)

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: |
             PersonHubApi/PersonHubApi.sln

    - task: DotNetCoreCLI@2
      displayName: Run Unit-test
      inputs:
        command: 'test'
        projects: |
            PersonHubApi/tests/PersonHub.UnitTest/PersonHub.UnitTest.csproj

    - task: DockerCompose@0
      displayName: Start dependencies (docker-compose)
      inputs:
        containerregistrytype: Container Registry
        dockerComposeFile: PersonHubApi/docker-compose.test.yaml
        dockerComposeCommand: 'up -d'

    - task: DotNetCoreCLI@2
      displayName: Run Integratin Test
      inputs:
        command: test
        projects: 'PersonHubApi/tests/PersonHub.IntegrationTest/PersonHub.IntegrationTest.csproj'
        arguments: '-c release --collect:"XPlat Code Coverage"'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/PersonHubApi/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: PublishBuildArtifacts@1
      displayName: Publish sql artifact
      inputs:
        pathToPublish: PersonHubApi/sql
        artifactName: sql

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: current
        artifact: sql
        path: $(Pipeline.Workspace)/sql

    - task: AzureWebAppContainer@1
      displayName: Deploy to Azure WebApp using container
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appServiceName)
        containers: $(imageName)
        appSettings:
          -DOCKER_REGISTRY_SERVER_USERNAME personhub
          -DOCKER_REGISTRY_SERVER_URL personhub.azurecr.io
          -DOCKER_REGISTRY_SERVER_PASSWORD $(dockerRegistryPassword)
