# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# specific path build
trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - PersonHubApi

resources:
- repo: self

pool:
  vmImage: Ubuntu-16.04

variables:
- group: person-hub-api
- name: tag
  value: '$(Build.BuildId)'
- name: imageRepository
  value: 'person-hub-api'
- name: appServiceName
  value: 'person-hub'
- name: dockerRegistryServiceConnection
  value: 'personhubACR'
- name: azureSubscription
  value: $(azure-subscription)

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: |
             PersonHubApi/PersonHubApi.sln

    - task: DotNetCoreCLI@2
      displayName: Run Unit-test
      inputs:
        command: 'test'
        projects: |
            PersonHubApi/tests/PersonHub.UnitTest/PersonHub.UnitTest.csproj

    - task: DockerCompose@0
      displayName: Start dependencies (docker-compose)
      inputs:
        containerregistrytype: Container Registry
        dockerComposeFile: PersonHubApi/docker-compose.test.yaml
        dockerComposeCommand: 'up -d'

    - task: DotNetCoreCLI@2
      displayName: Run Integratin Test
      inputs:
        command: test
        projects: 'PersonHubApi/tests/PersonHub.IntegrationTest/PersonHub.IntegrationTest.csproj'
        arguments: '-c release --collect:"XPlat Code Coverage"'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/PersonHubApi/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: AzureWebAppContainer@1
      displayName: Deploy to Azure WebApp using container
      inputs:
        azureSubscription: 'Visual Studio Enterprise Subscription – MPN (61b366e3-0ce9-49b1-b378-9b1ded00ef6d)'
        appName: $(appServiceName)
        containers: $(azureSubscription)
