# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# specific path build
trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - PersonHubApi

resources:
- repo: self

pool:
  vmImage: Ubuntu-16.04

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: |
             PersonHubApi/PersonHubApi.sln

    - task: DotNetCoreCLI@2
      displayName: Run Unit-test
      inputs:
        command: 'test'
        projects: |
            PersonHubApi/tests/PersonHub.UnitTest/PersonHub.UnitTest.csproj

    - task: DockerCompose@0
      displayName: Start dependencies (docker-compose)
      inputs:
        containerregistrytype: Container Registry
        dockerComposeFile: PersonHubApi/docker-compose.test.yaml
        dockerComposeCommand: 'up -d'

    - task: DotNetCoreCLI@2
      displayName: Run Integratin Test
      inputs:
        command: test
        projects: 'PersonHubApi/tests/PersonHub.IntegrationTest/PersonHub.IntegrationTest.csproj'
        arguments: '-c release --collect:"XPlat Code Coverage"'


  # - job: Build
  #   displayName: Build
  #   pool:
  #     vmImage: ubuntu-latest
  #   steps:
  #   - task: Docker@2
  #     displayName: Build an image
  #     inputs:
  #       command: build
  #       dockerfile: '$(Build.SourcesDirectory)/PersonHubApi/Dockerfile'
  #       tags: |
  #         $(tag)
