CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "TodoItems" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NULL,
    "Title" text NULL,
    "Description" text NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_TodoItems" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210628145941_InitialSchema', '5.0.5');

COMMIT;

