trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - person-hub-web

resources:
- repo: self

pool:
  vmImage: Ubuntu-16.04

variables:
- group: person-hub-web
- name: tag
  value: '$(Build.BuildId)'
- name: appServiceName
  value: 'person-hub-web'
- name: azureSubscription
  value: $(azure-subscription)
- name: storage-account
  value: personhub
- name: storage-container-name
  value: $web
- name: authentication-type
  value: AzureAdB2C

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: person-hub-web

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
        workingDir: person-hub-web

    - task: PublishBuildArtifacts@1
      displayName: Publish dist artifact
      inputs:
        pathToPublish: person-hub-web/dist
        artifactName: dist

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: current
        artifact: dist
        path: $(Pipeline.Workspace)/dist

    - task: AzureFileCopy@4
      inputs:
        sourcePath: $(Pipeline.Workspace)/dist
        azureSubscription: $(azureSubscription)
        destination: azureBlob
        storage: $(storage-account)
        containerName: $(storage-container-name)
