trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - person-hub-web

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
- group: person-hub-web
- name: tag
  value: '$(Build.BuildId)'
- name: appServiceName
  value: 'person-hub-web'
- name: azureSubscription
  value: $(azure-subscription)
- name: storage-account
  value: personhub
- name: authentication-type
  value: AzureAdB2C
- name: api-url
  value: https://person-hub-api.azurewebsites.net/

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: person-hub-web

    - script: |
        cd person-hub-web
        touch .env.production
        echo VUE_APP_AUTH_TYPE=AzureAdB2C >> .env.production
        echo VUE_APP_API_URL=$(api-url) >> .env.production
        cat .env.production
      displayName: Override env config file

    - script: |
        cat person-hub-web/.env.production
      displayName: Print content of .env.production file

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
        workingDir: person-hub-web

    - task: PublishBuildArtifacts@1
      displayName: Publish dist artifact
      inputs:
        pathToPublish: person-hub-web/dist
        artifactName: dist

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: current
        artifact: dist
        path: $(Pipeline.Workspace)/dist

    - task: AzureCLI@1
      displayName: Remove previous deployment in Azure Blob Storage
      inputs:
        azureSubscription: $(azure-subscription)
        scriptLocation: inlineScript
        inlineScript: |
          az storage blob delete-batch \
            --source \$web \
            --account-name "$(storage-account)"

    - task: AzureCLI@1
      displayName: Deploy the web to Azure Blob Storage
      inputs:
        azureSubscription: $(azure-subscription)
        scriptLocation: inlineScript
        inlineScript: |
          az storage blob upload-batch \
            --destination \$web \
            --account-name "$(storage-account)" \
            --source "$(Pipeline.Workspace)/dist"
