version: "3.9"
services:
  postgresdb:
    image: postgres:latest
    container_name: person-hub-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=person-hub-test
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    restart: on-failure

  flyway:
    container_name: flyway_person_hub
    image: flyway/flyway:7.12.1-alpine
    command: -url=jdbc:postgresql://postgresdb:5432/person-hub -schemas="person-hub" -user=postgres -password=P@ssw0rd migrate
    volumes:
      - sql:/flyway/sql
    depends_on:
      - postgresdb
    restart: on-failure

volumes:
    postgres:
