version: "3.9"
services:
  postgresql:
    image: postgres:latest
    container_name: person-hub-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      # - POSTGRES_DB=person-hub-db-test
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
      # - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
      # - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure

volumes:
    postgres:
