version: "3.9"
services:
  postgresql:
    image: postgres:latest
    container_name: person-hub-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=person-hub-db
      - PGDATA=/data/postgres
    volumes:
       - postgres:/data/postgres
    restart: on-failure

volumes:
    postgres:
