CREATE DATABASE IF NOT EXISTS "person-hub-db";
GRANT ALL PRIVILEGES ON DATABASE "person-hub-db" TO postgres;

CREATE TABLE "Test" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NULL,
    "Title" text NULL,
    "Description" text NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_TodoItems" PRIMARY KEY ("Id")
);
