name: .NET Web Api

on:
  push:
    branches: [ main ]
    paths:
    - PersonHubApi/**
    - .github/**

  pull_request:
    branches: [ main ]
    paths:
    - PersonHubApi/**
    - .github/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore PersonHubApi/PersonHubApi.sln
    - name: Build
      run: dotnet build PersonHubApi/PersonHubApi.sln --no-restore
    - name: Test
      run: dotnet test PersonHubApi/PersonHub.Api.IntegrationTest/PersonHub.Api.IntegrationTest.csproj --no-build --verbosity normal
