name: .NET Web Api

on:
  push:
    branches: [ main ]
    paths:
    - PersonHubApi/**
    - .github/workflows/api.yml

  pull_request:
    branches: [ main ]
    paths:
    - PersonHubApi/**
    - .github/workflows/api.yml

jobs:
  build:

    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: P@ssw0rd
          POSTGRES_DB: person-hub-db

        ports:
          # TEST TEST TEST
          - 5431:5432

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # - name: Start dependencies (docker-compose)
    #   run: docker-compose -f "PersonHubApi/docker-compose.test.yaml" up -d

    # - name: Wait for SQL Server container
    #   uses: jakejarvis/wait-action@master
    #   with:
    #     time: '5s'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore PersonHubApi/PersonHubApi.sln

    - name: Build
      run: dotnet build -c Release PersonHubApi/PersonHubApi.sln --no-restore

    - name: Test
      run: dotnet test -c Release PersonHubApi/PersonHub.Api.IntegrationTest/PersonHub.Api.IntegrationTest.csproj --no-build --verbosity normal --logger:"console;verbosity=detailed"
