name: .NET Web Api

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/api.yml'
    - 'PersonHubApi/**'
    - '!PersonHubApi/README.md'

  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/api.yml'
    - 'PersonHubApi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: person-hub-api
      POSTGRES_HOST: ${{ secrets.PERSON_HUB_DB_HOST }}
      POSTGRES_PORT: 5432
      POSTGRES_DB: person-hub
      POSTGRES_SCHEMA: person-hub
      POSTGRES_USER: ${{ secrets.PERSON_HUB_DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.PERSON_HUB_DB_PASSWORD }}
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      AUTHENTICATION_TYPE: Auth0

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Clean up dependencies (docker-compose)
      run: docker-compose -f "PersonHubApi/docker-compose.test.yaml" down --volumes

    - name: Start dependencies (docker-compose)
      run: docker-compose -f "PersonHubApi/docker-compose.test.yaml" up -d

    - name: Wait for SQL Server container
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore PersonHubApi/PersonHubApi.sln

    - name: Build
      run: |
        cd PersonHubApi
        dotnet build -c Release PersonHubApi.sln --no-restore

    - name: Run Unit Test
      run: dotnet test -c Release PersonHubApi/tests/PersonHub.UnitTest/PersonHub.UnitTest.csproj --no-build --verbosity normal --logger:"console;verbosity=detailed"

    - name: Run Integration Test
      run: dotnet test -c Release PersonHubApi/tests/PersonHub.IntegrationTest/PersonHub.IntegrationTest.csproj --no-build --verbosity normal --logger:"console;verbosity=detailed"

    - name: variable substitution in json, xml, and yml files
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: microsoft/variable-substitution@v1
      with:
        files: 'PersonHubApi/src/PersonHub.Api/appsettings.json'
      env:
        Authentication.ActiveImplementation: ${{ env.AUTHENTICATION_TYPE }}
        ApplicationSetting.AppName: ${{ env.APP_NAME }}
        DatabaseConnectionConfig.Host: ${{ env.POSTGRES_HOST }}
        DatabaseConnectionConfig.UserName: ${{ env.POSTGRES_USER }}
        DatabaseConnectionConfig.Password: ${{ env.POSTGRES_PASSWORD }}

    - name: Run Flyway Migration
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >-
        docker run --rm
        --volume ${{ github.workspace }}/PersonHubApi/sql:/flyway/sql
        flyway/flyway:7.12.1-alpine
        -url="jdbc:postgresql://${{ env.POSTGRES_HOST }}:${{ env.POSTGRES_PORT }}/${{ env.POSTGRES_DB }}?sslmode=require"
        -schemas=${{ env.POSTGRES_SCHEMA }}
        -user="${{ env.POSTGRES_USER }}"
        -password="${{ env.POSTGRES_PASSWORD }}"
        migrate

    - name: donet publish
      run: |
        cd PersonHubApi
        dotnet publish -c Release src/PersonHub.Api -o 'publish'         

    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.APP_NAME }} # Replace with your app name
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: 'PersonHubApi/publish'