name: Single Page Web App

on:
  push:
    branches: [ main ]
    paths:
    - person-hub-web/**
    - .github/workflows/spa-web.yml

  pull_request:
    branches: [ main ]
    paths:
    - person-hub-web/**
    - .github/workflows/spa-web.yml
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: person-hub
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Create env file
    #   run: |
    #       cd person-hub-web
    #       touch .env.production
    #       echo VITE_AUTH_TYPE=Auth0 >> .env.production
    #       cat .env.production

    - name: Check whether there are any valid cached dependencies (to reduce execution time)
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Build
      run: |
        cd person-hub-web
        npm ci
        npm run build
    
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './person-hub-web/dist'
        production-branch: main
        production-deploy: true
        deploy-message: "Prod deploy v${{ github.ref }}"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 5